### ISSUE TITLE
Update README for instructions on how to run it in conjunction with the budget-angular

### ISSUE THREAD

**Issue by chan-dev** [bartosz-io/budget-node#1]
I feel like instructions should be included on how to run it with the frontend part. Should both be within the same project root? What are other prerequisites needed?

I just cloned both this repo and the **budget-angular** repo and i currently can't make it work. And from looking at the source it seems like they should be within the same project.

Here's a snippet from the `src/index.ts`
```
app.use(express.static('../angular/dist/'));
```

and it uses the build version generated with `ng build --prod`?

**Comment by bartosz-io** [comment]
I have created a Readme file in [budget-angular](https://github.com/bartosz-io/budget-angular#running).
